---
layout: default
title: "Pistol Pete"
cowboy: "JohnSwartzwelder.com"
type: "Watchin"
date: 2021-02-20
photo: "https://raw.githubusercontent.com/CowboyCollective/media/master/PistolPete.png"
---

Once considered only myth and rumor, you can now finally view the entire 1996 John Swartzwelder TV pilot episode “Pistol Pete” in its entirety. Much has been said about Pistol Pete and with Westerns being long out of favor the appeal of a TV Western comedy might be hard to explain to kids today. To anyone who has already seen it Swartzwelder himself says “okay, wise guy, you try and make a Western”.

<br><br>
![Photo](https://johnswartzwelder.com/wp-content/uploads/2020/08/PIstol_Pete_Maravich_1970.jpg)
*The pilot has nothing to do with pro NBA player Peter “Pistol Pete” Maravich*

Town mayor, played by veteran comedy actor Brian Doyle-Murray, needs to hire someone to protect his town from all kinds of brazen outlaws and “luckily” he manages to convince Pistol Pete, played by Australian stage actor Stephen Kearney, to become the new town sheriff. Pistol Pete is traveling marksman one of the world’s leading buffoons. But that’s no problem for the average townsperson, who are improbably even stupider than Pistol Pete.
 
As is often the case with pilot episodes, had Pistol Pete been picked up for broadcast it may have gone on to be drastically changed from this pilot episode. There is no way to know what Pistol Pete could have eventually been, unless you somehow traveled to an alternate universe where Pistol Pete was picked up and became a massive hit. Swartzwelders season 13 episode of the Simpsons [The Lastest Gun in the West](https://johnswartzwelder.com/simpsons/episodes/s13e12/), as well as his novel [Double Wonderful](https://johnswartzwelder.com/books/double-wonderful/), showed that he still had a lot of love and laughs in him for Westerns and offers us the first hints that maybe there was something more to Swartzwelder’s grand vision for an quirky comedy western than first meets the eye.

Now gather the family and watch the Pistol Pete pilot in its entirety so you can decide for yourself.

<iframe src="https://archive.org/embed/pistol-pete" style="youtube" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>

<h1>An Idea Decades in the Making</h1>

If Pistol Pete seems like a show that is decades older than 1996, then that is due to Swartzwelder’s very specific vision for the production of the show. He wanted the world of Pistol Pete to look and feel like the hit Western TV show Gunsmoke, which ran from 1955 to 1975. Gunsmoke was a television institution, a pulp Western aimed at adults that still to this day holds the record for having the highest number of scripted episodes out of any live-action primetime US TV series (The Simpsons finally took the record from Gunsmoke of most scriped episodes in any-format primetime series in 2018). Swartzwelder even hired as many of the production crew who worked on Gunsmoke as he could. This shows the level of  his dedication to achieving his vision of a comedy Western that looks like a faithful western that you’re always seeing rerun on TV, but filled with jokes that meet modern expectations of increasingly quirky television. Pistol Pete’s concept was years ahead of anything else on primetime television at that point in the 90s. Gunsmoke in the 90s was still a mainstream television institution that audiences took for granted, thanks to Gunsmoke’s wide syndication of repeats.

Even the director of the pilot was chosen for his history with Gunsmoke; director John Rich had himself directed 14 episodes of Gunsmoke, as well as directing many other American TV institutions such as All in the Family, Hogan’s Heroes, The Dick Van Dyke Show, and Gilligan’s Island to name just a few. However, John Rich was in his 70s when he directed the Pistol Pete pilot. His youth long behind him, he was at the very end of his directing career and was spending most of his time being the owner of his own production company as well as serving as vice president of the Director’s Guild. Having a figure such as John Rich directing was a great honor and rare opportunity for the rest of the cast and crew. Between takes on the set Rich would regale those around him about his wealth of experience working in television. Principal actors later reminisced that Rich may not have actually been the best choice to direct the project. Due to his age at the time John Rich could often not stand up from his director’s chair which was by necessity a great distance from the set. However, there is no doubting that the visual production of Pistol Pete had achieved the desired results of looking like a genuine Hollywood Western production from yesteryear.

With production crew, director, and actors secured, the pilot was soon ready to shoot. Stephen Kearney, a stage actor originally from Australia, had never handled a pistol in his life and worried that his inexperience with firearms may not play with Pistol Pete being one of the world’s greatest marksmen. The script called for all kinds of gun tricks so Kearney was eventually set up with a half an hour session with one of the Western performers at Universal Studios, where he received a primer on how to sling a prop gun.

If gun experience was assumed to be easy to pick up, then horse riding wasn’t as more extensive training was offered to the actors. Expert horse riding stuntmen could effortlessly perform long shots in the days of standard definition TV, but plenty of shots would require close-ups of the actors on horses. Actors were taken to a ranch where they could train how to handle a horse, such as learning how to mount and dismount a horse naturally.

<h1>Misfire</h1>

> “Pistol fucking Pete?!?” – Mark Derwin (Deputy Langley) on being asked about Pistol Pete in 2013

But alas Pistol Pete never was picked up. Perhaps if Fox had a better understanding of Swartzwelder’s vision for his new series they may have given it a chance. He had planned for a number of other Simpsons writers to come in and write episodes for future episodes of Pistol Pete. He and the other Simpsons writers he talked to had jokes planned out for the future of Pistol Pete, realizing that they could spoof any western they liked for any particular joke or episode. It’s not hard to share Swartzwelder and his fellow writer’s enthusiasm for the concept and imagine to imagine what the show could have offered by season two, with Swartzwelder’s vision more fully realized when the writers and audience would have had a good feel for the show’s format and each actor’s comedic timing.

***Swartzwelder realized that Pistol Pete could spoof every Western ever made so there would be no shortage of material for jokes.***

Stephen Kearney reports that what he saw in the final cut of the Pistol Pete pilot did not match what he was expecting, the way the show was edited he felt lacked the comedic “simpsons punch” pace of comedy he was expecting based on conversations with Swartzwelder and his vision for the series. Kearney still feels the pilot had a lot of potential and compares it to the first season of Seinfeld, which is a far cry from the successful format Seinfeld later evolved into.

Kearney later learned that at the time Rupert Murdoch, owner and head of Fox, personally reviewed Fox’s pilots. Apparently Rupert was feeling tired by the time Pistol Pete was on and turned it off.

A lot of people had a lot of faith in Swartzwelder’s Pistol Pete series and his vision was communicated very well to those who worked on the project. There was a lot of surprise that it wasn’t picked up. There was nothing else like it at the time and Fox had made a name for itself by backing shows that break convention and are a bit quirky. But one thing that is clear to fans of Swartzwelder’s brand of humor is that the pilot episode by itself did not adequately capture his comedic vision for the series future. The form the show was in for the pilot didn’t have the same fast pace of jokes that fans of his were accustomed to. The reasons for this aren’t known; perhaps Swartzwelder or director John Rich were worried that too many fast paced jokes at once would alienate actual Western fans, who could have made up a key demographic for the ongoing future of the series. Perhaps Swartzwelder intentionally wanted a gentle introduction to the series, to allow him and his writers to eventually build up to Swartzwelder’s brand of comedic absurdism only after the viewer has had the opportunity to understand and accept the characters and premise. Until John Swartzwelder publishes his 10,000 page mémoire, the world can only speculate as to exactly why the Pistol Pete pilot arrived in the form that it did or how close it was to Swartzwelder’s ultimate vision for the series.

Swartzwelder was a mover and shaker in the TV world. The pilot for Pistol Pete reportedly cost over three million dollars to produce at the time. Hopes were high that Pistol Pete would be picked up even at the 11th hour, but when it was definitively turned down it came as a genuine surprise to those who worked on it. Director John Rich personally called the actors to break the news, even leaving a 15 minute heartfelt message for an actor who wasn’t immediately available to take his call. On Pistol Pete’s pilot episode reception, John Rich reportedly countered that All in the Family was the worst received pilot in TV history, but pointed out that it went on to become arguably one of the best and most profitable sitcoms of all time. This echoed the view of many who worked on Pistol Pete who believed it had the makings of a big hit and were fully expecting to be enduring 100 degree weather in hot cowboy leather for the next seven years.

<br><br><br>*EDITOR'S NOTE: This article originally appeared at [JohnSwartzwelder.com](https://johnswartzwelder.com/pistol-pete/) and is reproduced here with permission. The pilot is under copyright, but in a grey area because it has been abandoned by the copyright holders and is considered an "[Orphan Work](https://www.copyright.gov/docs/regstat031308.html)"*
